### ISSUE TITLE
Runtime Error With Text Boxes 

### ISSUE THREAD

**Issue by AmithisCurious** [chuhaojin/Text2Poster-ICASSP-22#8]

**Comment by AmithisCurious** [comment]
envs\torch\lib\site-packages\torch\_ops.py", line 502, in __call__
    return self._op(*args, **kwargs or {})
RuntimeError: boxes should be a 2d tensor, got 1D
I get this error while running the code on custom .jpeg images that are of 1024x768px, Any guidance to how this error is originated? or any resolves?

**Comment by xuboot** [comment]
@AmithisCurious 你输入的文字和大小超过了图片边框了
